// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildUsuariosWithMapping(arg1:Array<main.MappingItem>):Promise<Record<number, main.ValidationResult>>;

export function Greet(arg1:string):Promise<string>;

export function SuggestMapping(arg1:Array<number>,arg2:number):Promise<Array<main.MappingItem>>;
