// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildUsuariosWithMapping(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildUsuariosWithMapping'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SuggestMapping(arg1, arg2) {
  return window['go']['main']['App']['SuggestMapping'](arg1, arg2);
}
