// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAvaliadoresWithMapping(arg1) {
  return window['go']['main']['App']['BuildAvaliadoresWithMapping'](arg1);
}

export function BuildRestricoesWithMapping(arg1) {
  return window['go']['main']['App']['BuildRestricoesWithMapping'](arg1);
}

export function BuildUsuariosWithMapping(arg1) {
  return window['go']['main']['App']['BuildUsuariosWithMapping'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveRestricoesFromMaps(arg1) {
  return window['go']['main']['App']['SaveRestricoesFromMaps'](arg1);
}

export function SaveUsuariosFromMaps(arg1) {
  return window['go']['main']['App']['SaveUsuariosFromMaps'](arg1);
}

export function SuggestMapping(arg1, arg2) {
  return window['go']['main']['App']['SuggestMapping'](arg1, arg2);
}

export function SuggestMappingAvaliador() {
  return window['go']['main']['App']['SuggestMappingAvaliador']();
}

export function SuggestMappingRestricao() {
  return window['go']['main']['App']['SuggestMappingRestricao']();
}
