// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAllocationConfiguration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildAllocationConfiguration'](arg1, arg2, arg3, arg4);
}

export function BuildAllocationConfigurationFromDatabase(arg1) {
  return window['go']['main']['App']['BuildAllocationConfigurationFromDatabase'](arg1);
}

export function BuildAvaliadoresWithMapping(arg1) {
  return window['go']['main']['App']['BuildAvaliadoresWithMapping'](arg1);
}

export function BuildRestricoesWithMapping(arg1) {
  return window['go']['main']['App']['BuildRestricoesWithMapping'](arg1);
}

export function BuildUsuariosWithMapping(arg1) {
  return window['go']['main']['App']['BuildUsuariosWithMapping'](arg1);
}

export function CountPossibleAllocationQuantities(arg1, arg2) {
  return window['go']['main']['App']['CountPossibleAllocationQuantities'](arg1, arg2);
}

export function CountPossibleAllocationQuantitiesAcrossSchedules(arg1, arg2, arg3) {
  return window['go']['main']['App']['CountPossibleAllocationQuantitiesAcrossSchedules'](arg1, arg2, arg3);
}

export function DefaultAllocationParams() {
  return window['go']['main']['App']['DefaultAllocationParams']();
}

export function DetectUniqueCandidateColumnValues(arg1, arg2) {
  return window['go']['main']['App']['DetectUniqueCandidateColumnValues'](arg1, arg2);
}

export function DetectUniquePreferenceValues(arg1) {
  return window['go']['main']['App']['DetectUniquePreferenceValues'](arg1);
}

export function GetAvaliadorMappingFieldInfos() {
  return window['go']['main']['App']['GetAvaliadorMappingFieldInfos']();
}

export function GetCandidateMappingFieldInfos() {
  return window['go']['main']['App']['GetCandidateMappingFieldInfos']();
}

export function GetCriteriaOptions() {
  return window['go']['main']['App']['GetCriteriaOptions']();
}

export function GetRestricaoMappingFieldInfos() {
  return window['go']['main']['App']['GetRestricaoMappingFieldInfos']();
}

export function GetSoftCriterionOptions() {
  return window['go']['main']['App']['GetSoftCriterionOptions']();
}

export function GetWorkflowDefinition() {
  return window['go']['main']['App']['GetWorkflowDefinition']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCandidateCriterionColumns(arg1) {
  return window['go']['main']['App']['ListCandidateCriterionColumns'](arg1);
}

export function NormalizePreferenceScheduleMappings(arg1) {
  return window['go']['main']['App']['NormalizePreferenceScheduleMappings'](arg1);
}

export function NormalizeSoftCriteria(arg1) {
  return window['go']['main']['App']['NormalizeSoftCriteria'](arg1);
}

export function RunAllocation(arg1) {
  return window['go']['main']['App']['RunAllocation'](arg1);
}

export function SaveAvaliadoresFromMaps(arg1) {
  return window['go']['main']['App']['SaveAvaliadoresFromMaps'](arg1);
}

export function SaveRestricoesFromMaps(arg1) {
  return window['go']['main']['App']['SaveRestricoesFromMaps'](arg1);
}

export function SaveUsuariosFromMaps(arg1) {
  return window['go']['main']['App']['SaveUsuariosFromMaps'](arg1);
}

export function SuggestMapping(arg1, arg2) {
  return window['go']['main']['App']['SuggestMapping'](arg1, arg2);
}

export function SuggestMappingAvaliador() {
  return window['go']['main']['App']['SuggestMappingAvaliador']();
}

export function SuggestMappingRestricao() {
  return window['go']['main']['App']['SuggestMappingRestricao']();
}

export function ValidateAllocationParams(arg1, arg2) {
  return window['go']['main']['App']['ValidateAllocationParams'](arg1, arg2);
}

export function ValidatePreferenceScheduleMappings(arg1) {
  return window['go']['main']['App']['ValidatePreferenceScheduleMappings'](arg1);
}

export function ValidateSoftCriteria(arg1, arg2) {
  return window['go']['main']['App']['ValidateSoftCriteria'](arg1, arg2);
}
