// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {logic} from '../models';

export function BuildAvaliadoresWithMapping(arg1:Array<types.MappingItem>):Promise<logic.AvaliadoresResponse>;

export function BuildRestricoesWithMapping(arg1:Array<types.MappingItem>):Promise<Array<types.Restricao>>;

export function BuildUsuariosWithMapping(arg1:Array<types.MappingItem>):Promise<logic.UsuariosResponse>;

export function GetAvaliadorMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function GetCandidateMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function GetRestricaoMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function Greet(arg1:string):Promise<string>;

export function SaveAvaliadoresFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveRestricoesFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveUsuariosFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SuggestMapping(arg1:Array<number>,arg2:number):Promise<Array<types.MappingItem>>;

export function SuggestMappingAvaliador():Promise<Array<types.MappingItem>>;

export function SuggestMappingRestricao():Promise<Array<types.MappingItem>>;
