// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildAvaliadoresWithMapping(arg1:Array<main.MappingItem>):Promise<Array<main.AvaliadorInfo>>;

export function BuildRestricoesWithMapping(arg1:Array<main.MappingItem>):Promise<Array<main.Restricao>>;

export function BuildUsuariosWithMapping(arg1:Array<main.MappingItem>):Promise<main.UsuariosResponse>;

export function Greet(arg1:string):Promise<string>;

export function SaveUsuariosFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SuggestMapping(arg1:Array<number>,arg2:number):Promise<Array<main.MappingItem>>;

export function SuggestMappingAvaliador():Promise<Array<main.MappingItem>>;

export function SuggestMappingRestricao():Promise<Array<main.MappingItem>>;
