// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAvaliadoresWithMapping(arg1) {
  return window['go']['main']['App']['BuildAvaliadoresWithMapping'](arg1);
}

export function BuildRestricoesWithMapping(arg1) {
  return window['go']['main']['App']['BuildRestricoesWithMapping'](arg1);
}

export function BuildUsuariosWithMapping(arg1) {
  return window['go']['main']['App']['BuildUsuariosWithMapping'](arg1);
}

export function ExportResultado() {
  return window['go']['main']['App']['ExportResultado']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetApp() {
  return window['go']['main']['App']['ResetApp']();
}

export function RunAlocacao() {
  return window['go']['main']['App']['RunAlocacao']();
}

export function SaveAvaliadores(arg1) {
  return window['go']['main']['App']['SaveAvaliadores'](arg1);
}

export function SaveRestricoes(arg1) {
  return window['go']['main']['App']['SaveRestricoes'](arg1);
}

export function SaveUsuarios(arg1) {
  return window['go']['main']['App']['SaveUsuarios'](arg1);
}

export function SetupDB() {
  return window['go']['main']['App']['SetupDB']();
}

export function SuggestMapping(arg1, arg2) {
  return window['go']['main']['App']['SuggestMapping'](arg1, arg2);
}

export function SuggestMappingAvaliador() {
  return window['go']['main']['App']['SuggestMappingAvaliador']();
}

export function SuggestMappingRestricao() {
  return window['go']['main']['App']['SuggestMappingRestricao']();
}
