// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {logic} from '../models';
import {main} from '../models';

export function BuildAllocationConfiguration(arg1:Array<types.UniqueValueDetection>,arg2:Array<types.PreferenceScheduleMapping>,arg3:types.AllocationParams,arg4:Array<types.Candidato>):Promise<types.AllocationConfiguration>;

export function BuildAllocationConfigurationFromDatabase(arg1:types.AllocationParams):Promise<types.AllocationConfiguration>;

export function BuildAvaliadoresWithMapping(arg1:Array<types.MappingItem>):Promise<logic.AvaliadoresResponse>;

export function BuildRestricoesWithMapping(arg1:Array<types.MappingItem>):Promise<Array<types.Restricao>>;

export function BuildUsuariosWithMapping(arg1:Array<types.MappingItem>):Promise<logic.UsuariosResponse>;

export function CountPossibleAllocationQuantities(arg1:types.AllocationParams,arg2:number):Promise<number>;

export function CountPossibleAllocationQuantitiesAcrossSchedules(arg1:types.AllocationParams,arg2:number,arg3:number):Promise<number>;

export function DefaultAllocationParams():Promise<types.AllocationParams>;

export function DetectUniqueCandidateColumnValues(arg1:Array<types.Candidato>,arg2:string):Promise<Array<types.UniqueValueDetection>>;

export function DetectUniquePreferenceValues(arg1:Array<types.Candidato>):Promise<Array<types.UniqueValueDetection>>;

export function GetAvaliadorMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function GetCandidateMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function GetCriteriaOptions():Promise<Record<string, Array<string>>>;

export function GetRestricaoMappingFieldInfos():Promise<Array<types.MappingFieldInfo>>;

export function GetSoftCriterionOptions():Promise<Array<types.SoftCriterionOption>>;

export function GetWorkflowDefinition():Promise<types.WorkflowDefinition>;

export function Greet(arg1:string):Promise<string>;

export function ListCandidateCriterionColumns(arg1:Array<types.Candidato>):Promise<Array<types.CandidateCriterionColumn>>;

export function NormalizePreferenceScheduleMappings(arg1:Array<types.PreferenceScheduleMapping>):Promise<Array<types.PreferenceScheduleMapping>>;

export function NormalizeSoftCriteria(arg1:Array<types.SoftCriterion>):Promise<Array<types.SoftCriterion>>;

export function RunAllocation(arg1:types.AllocationConfiguration):Promise<main.UIAllocationResult>;

export function SaveAvaliadoresFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveRestricoesFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveUsuariosFromMaps(arg1:Array<Record<string, any>>):Promise<void>;

export function StartAllocation(arg1:types.AllocationConfiguration):Promise<void>;

export function StopAllocation():Promise<boolean>;

export function SuggestMapping(arg1:Array<number>,arg2:number):Promise<Array<types.MappingItem>>;

export function SuggestMappingAvaliador():Promise<Array<types.MappingItem>>;

export function SuggestMappingRestricao():Promise<Array<types.MappingItem>>;

export function ValidateAllocationParams(arg1:types.AllocationParams,arg2:Array<types.Candidato>):Promise<void>;

export function ValidatePreferenceScheduleMappings(arg1:Array<types.PreferenceScheduleMapping>):Promise<void>;

export function ValidateSoftCriteria(arg1:Array<types.SoftCriterion>,arg2:Array<types.Candidato>):Promise<void>;
